#!/bin/bash

banner_echo() {
  echo "-------------------------------------------"
  echo -e "$*"
  echo "-------------------------------------------"
}

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo "Running git pre-commit hook .."

LINT_OUTPUT=$(./gradlew detektAll)
LINT_RESULT=$?

if [[ $LINT_RESULT -ne 0 ]]; then
  echo "$LINT_OUTPUT"
  banner_echo "${RED} Code linting failed.${NC}"
  exit 1
else
  banner_echo "${GREEN} Everything is ok. Commit has been done ${NC}"
  exit 0
fi
